// Generated from raoh-specification's catalog/messages by packages/wasm/scripts/catalog.py,
// at b38ded05f2a68e45849d38494ddc2aa34640aad1. Do not edit: regenerate from the catalog instead.
//
// The catalog is Raoh's, Apache License 2.0 (https://github.com/raoh-project/raoh-specification).

/** Each locale's templates, by the key a message is looked up under. */
export const CATALOG: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "en": {
    "raoh.required": "is required",
    "raoh.blank": "must not be blank",
    "raoh.too_short": "must be at least {min} characters",
    "raoh.too_long": "must be at most {max} characters",
    "raoh.invalid_length": "must be exactly {expected} characters",
    "raoh.out_of_range": "must be between {min} and {max}",
    "raoh.out_of_range.minimum": "must be at least {min}",
    "raoh.out_of_range.maximum": "must be at most {max}",
    "raoh.out_of_range.range": "must be between {min} and {max}",
    "raoh.out_of_range.positive": "must be positive",
    "raoh.out_of_range.negative": "must be negative",
    "raoh.out_of_range.non_negative": "must be non-negative",
    "raoh.out_of_range.non_positive": "must be non-positive",
    "raoh.out_of_range.before": "must be before {before}",
    "raoh.out_of_range.after": "must be after {after}",
    "raoh.out_of_range.between": "must be between {from} and {to}",
    "raoh.not_multiple_of": "must be a multiple of {divisor}",
    "raoh.invalid_scale": "too many decimal places (max {maxScale})",
    "raoh.too_small": "must have at least {min} elements",
    "raoh.too_small.nonempty": "must not be empty",
    "raoh.too_big": "must have at most {max} elements",
    "raoh.invalid_size": "must have exactly {expected} elements",
    "raoh.invalid_value": "must be {expected}",
    "raoh.missing_element": "must contain {expected}",
    "raoh.missing_elements": "must contain all of {expected} (missing: {missing})",
    "raoh.duplicate_element": "must not contain duplicates: {duplicates}",
    "raoh.not_allowed": "must be one of {allowed}",
    "raoh.invalid_format": "invalid format",
    "raoh.invalid_format.email": "not a valid email",
    "raoh.invalid_format.url": "not a valid URL",
    "raoh.invalid_format.uri": "not a valid URI",
    "raoh.invalid_format.uuid": "not a valid UUID",
    "raoh.invalid_format.ip": "not a valid IP address",
    "raoh.invalid_format.ipv4": "not a valid IPv4 address",
    "raoh.invalid_format.ipv6": "not a valid IPv6 address",
    "raoh.invalid_format.ulid": "not a valid ULID",
    "raoh.invalid_format.cuid": "not a valid CUID",
    "raoh.invalid_format.starts_with": "must start with \"{prefix}\"",
    "raoh.invalid_format.ends_with": "must end with \"{suffix}\"",
    "raoh.invalid_format.includes": "must include \"{substring}\"",
    "raoh.invalid_format.enum": "invalid value",
    "raoh.invalid_format.literal": "invalid value",
    "raoh.invalid_format.instant": "not a valid ISO 8601 instant",
    "raoh.invalid_format.date": "not a valid ISO-8601 date (e.g., 2024-01-15)",
    "raoh.invalid_format.time": "not a valid ISO-8601 local time (e.g., 10:30 or 10:30:45)",
    "raoh.invalid_format.date_time": "not a valid ISO-8601 local date-time (e.g., 2024-01-15T10:30 or 2024-01-15T10:30:45)",
    "raoh.invalid_format.offset_date_time": "not a valid ISO-8601 offset date-time (e.g., 2024-01-15T10:30:00+09:00)",
    "raoh.type_mismatch": "expected {expected}",
    "raoh.type_mismatch.string_keys": "expected object with string keys, found {actual} key",
    "raoh.type_mismatch.numeric_range": "value is outside the {expected} range",
    "raoh.unknown_field": "unknown field",
    "raoh.one_of_failed": "no variant matched",
    "raoh.missing_field": "field is missing",
  },
  "ja": {
    "raoh.required": "必須です",
    "raoh.blank": "空白は許可されていません",
    "raoh.too_short": "{min}文字以上で入力してください",
    "raoh.too_long": "{max}文字以内で入力してください",
    "raoh.invalid_length": "{expected}文字で入力してください",
    "raoh.out_of_range": "{min}以上{max}以下で入力してください",
    "raoh.out_of_range.minimum": "{min}以上で入力してください",
    "raoh.out_of_range.maximum": "{max}以下で入力してください",
    "raoh.out_of_range.range": "{min}以上{max}以下で入力してください",
    "raoh.out_of_range.positive": "正の値で入力してください",
    "raoh.out_of_range.negative": "負の値で入力してください",
    "raoh.out_of_range.non_negative": "0以上で入力してください",
    "raoh.out_of_range.non_positive": "0以下で入力してください",
    "raoh.out_of_range.before": "{before}より前で入力してください",
    "raoh.out_of_range.after": "{after}より後で入力してください",
    "raoh.out_of_range.between": "{from}から{to}の範囲で入力してください",
    "raoh.not_multiple_of": "{divisor}の倍数で入力してください",
    "raoh.invalid_scale": "小数点以下は{maxScale}桁までです",
    "raoh.too_small": "{min}個以上の要素が必要です",
    "raoh.too_small.nonempty": "空にはできません",
    "raoh.too_big": "{max}個以内の要素が必要です",
    "raoh.invalid_size": "{expected}個の要素が必要です",
    "raoh.invalid_value": "{expected}でなければなりません",
    "raoh.missing_element": "{expected}を含む必要があります",
    "raoh.missing_elements": "{expected}をすべて含む必要があります（不足: {missing}）",
    "raoh.duplicate_element": "重複があります: {duplicates}",
    "raoh.not_allowed": "{allowed}のいずれかで入力してください",
    "raoh.invalid_format": "形式が不正です",
    "raoh.invalid_format.email": "メールアドレスの形式が不正です",
    "raoh.invalid_format.url": "URLの形式が不正です",
    "raoh.invalid_format.uri": "URIの形式が不正です",
    "raoh.invalid_format.uuid": "UUIDの形式が不正です",
    "raoh.invalid_format.ip": "IPアドレスの形式が不正です",
    "raoh.invalid_format.ipv4": "IPv4アドレスの形式が不正です",
    "raoh.invalid_format.ipv6": "IPv6アドレスの形式が不正です",
    "raoh.invalid_format.ulid": "ULIDの形式が不正です",
    "raoh.invalid_format.cuid": "CUIDの形式が不正です",
    "raoh.invalid_format.starts_with": "「{prefix}」で始まる必要があります",
    "raoh.invalid_format.ends_with": "「{suffix}」で終わる必要があります",
    "raoh.invalid_format.includes": "「{substring}」を含む必要があります",
    "raoh.invalid_format.enum": "値が不正です",
    "raoh.invalid_format.literal": "値が不正です",
    "raoh.invalid_format.instant": "日時の形式が不正です（例: 2024-01-15T01:30:00Z）",
    "raoh.invalid_format.date": "日付の形式が不正です（例: 2024-01-15）",
    "raoh.invalid_format.time": "時刻の形式が不正です（例: 10:30 または 10:30:45）",
    "raoh.invalid_format.date_time": "日時の形式が不正です（例: 2024-01-15T10:30 または 2024-01-15T10:30:45）",
    "raoh.invalid_format.offset_date_time": "オフセット付き日時の形式が不正です（例: 2024-01-15T10:30:00+09:00）",
    "raoh.type_mismatch": "{expected}型が必要です",
    "raoh.type_mismatch.string_keys": "キーがすべて文字列のオブジェクトが必要です（キーの型: {actual}）",
    "raoh.type_mismatch.numeric_range": "{expected}型の範囲外の値です",
    "raoh.unknown_field": "不明なフィールドです",
    "raoh.one_of_failed": "いずれのバリアントにも一致しませんでした",
    "raoh.missing_field": "フィールドが見つかりません",
  },
};
