// A TypeScript binding of a Souther program, written from what its module says it offers.
//
// Everything written here is read off the module's surface: the types its values cross as, the
// behaviors it offers, what it reaches out for, and the types a caller may read a value of on its
// own. Nothing about a model is decided here, so a case renamed in the model is a type renamed in
// the binding, and a page that still names the old one does not compile.

import type { Declaration, Form, Shape, Surface } from "./surface.ts";

/** How a primitive standing as a case of an answer is tagged: by its name in the language. */
const PRIMITIVE_TAGS: Readonly<Record<string, string>> = {
  string: "String", int: "Int", bool: "Bool", decimal: "Decimal",
  date: "Date", time: "Time", datetime: "DateTime", instant: "Instant",
};

/**
 * The binding of a module whose surface is `surface`, as TypeScript source.
 *
 * @param fingerprint what identifies the surface (`fingerprintOf`), which the binding refuses any
 *     other module than one carrying
 * @param runtime what the binding imports the runtime as
 */
export function bindingFor(surface: Surface, fingerprint: string, runtime = "@souther/wasm"): string {
  const names = namesOf(surface.declarations);
  const declared = new Map(surface.declarations.map((each) => [key(each), each]));
  const typeOf = (shape: Shape): string => written(shape, names, declared);
  const out: string[] = [
    "// Generated by @souther/wasm from a module's souther:surface. Do not edit: generate it again",
    "// from the module instead.",
    "",
    `import { load as loaded, type Numeric, type Program, type Reading } from ${JSON.stringify(runtime)};`,
    "",
    "/** What identifies the surface this binding was generated from; a module carrying another is refused. */",
    `export const FINGERPRINT = ${JSON.stringify(fingerprint)};`,
    "",
  ];

  for (const declaration of surface.declarations) {
    out.push(`/** \`${declaration.module}.${declaration.name}\`${declaration.published === false ? ", which its module keeps" : ""}. */`);
    out.push(`export type ${names.get(key(declaration))} = ${declarationType(declaration, typeOf, names, declared)};`);
    out.push("");
  }

  // What the host has to supply is every behavior the program reaches out for, whether its module
  // publishes it or keeps it: a kept one is reached for all the same.
  const reaching = surface.modules.flatMap((module) => module.behaviors
    .filter((behavior) => behavior.reachOut !== undefined)
    .map((behavior) => ({ behavior, named: `${module.name}.${behavior.name}` })));
  out.push("/** What answers each behavior the program reaches out for. */");
  out.push("export interface Supplied {");
  for (const { behavior, named } of reaching) {
    out.push(`  readonly ${JSON.stringify(named)}: (${parameters(behavior.parameters, typeOf)}) => ${typeOf(behavior.answers)};`);
  }
  out.push("}");
  out.push("");

  out.push("/** The program, loaded: each module's behaviors, and each type a value can be read as on its own. */");
  out.push("export interface Bound {");
  out.push("  readonly program: Program;");
  for (const module of surface.modules) {
    const offered = module.behaviors.filter((behavior) => behavior.export !== undefined && behavior.reachOut === undefined);
    out.push(`  readonly ${property(module.name)}: {`);
    for (const behavior of offered) {
      out.push(`    ${property(behavior.name)}(${parameters(behavior.parameters, typeOf)}): Reading<${typeOf(behavior.answers)}>;`);
    }
    out.push("  };");
  }
  out.push("  readonly decode: {");
  for (const declaration of surface.declarations.filter((each) => each.decode !== undefined)) {
    out.push(`    ${names.get(key(declaration))}(value: unknown): Reading<${names.get(key(declaration))}>;`);
  }
  out.push("  };");
  out.push("}");
  out.push("");

  const optional = reaching.length === 0 ? " = {} as Supplied" : "";
  out.push("/** Loads the module this binding was generated from, and refuses any other. */");
  out.push(`export async function load(source: Parameters<typeof loaded>[0], supplied: Supplied${optional}): Promise<Bound> {`);
  out.push("  const program = await loaded(source, supplied as unknown as Parameters<typeof loaded>[1], FINGERPRINT);");
  out.push("  const bound: Bound = {");
  out.push("    program,");
  for (const module of surface.modules) {
    const offered = module.behaviors.filter((behavior) => behavior.export !== undefined && behavior.reachOut === undefined);
    out.push(`    ${property(module.name)}: {`);
    for (const behavior of offered) {
      const names = behavior.parameters.map((each, at) => each.name ?? `argument${at}`);
      out.push(`      ${property(behavior.name)}: (${names.join(", ")}) => program.call(${JSON.stringify(behavior.export as string)}, [${names.join(", ")}]),`);
    }
    out.push("    },");
  }
  out.push("    decode: {");
  for (const declaration of surface.declarations.filter((each) => each.decode !== undefined)) {
    out.push(`      ${names.get(key(declaration))}: (value) => program.decode(${JSON.stringify(key(declaration))}, value),`);
  }
  out.push("    },");
  out.push("  };");
  out.push("  return bound;");
  out.push("}");
  return out.join("\n") + "\n";
}

/** A property's name as TypeScript writes it: bare where it can be, quoted where it cannot. */
function property(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function key(declaration: { module: string; name: string }): string {
  return `${declaration.module}.${declaration.name}`;
}

/**
 * What each declaration is called in the binding: its own name, and its module's before it where
 * two modules declare the same one, since a type is its module and its name.
 */
function namesOf(declarations: readonly Declaration[]): Map<string, string> {
  const count = new Map<string, number>();
  for (const each of declarations) {
    count.set(each.name, (count.get(each.name) ?? 0) + 1);
  }
  return new Map(declarations.map((each) => [key(each), (count.get(each.name) ?? 0) > 1
    ? each.module.split(".").map(capitalised).join("") + each.name
    : each.name]));
}

function capitalised(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function parameters(
  declared: readonly { readonly name: string | null; readonly type: Shape }[],
  typeOf: (shape: Shape) => string,
): string {
  return declared.map((each, at) => `${each.name ?? `argument${at}`}: ${typeOf(each.type)}`).join(", ");
}

function declarationType(
  declaration: Declaration,
  typeOf: (shape: Shape) => string,
  names: Map<string, string>,
  declared: Map<string, Declaration>,
): string {
  switch (declaration.is) {
    case "product": {
      const fields = declaration.fields.map((field) => field.type.is === "option"
        ? `readonly ${property(field.name)}?: ${typeOf(field.type.of)}`
        : `readonly ${property(field.name)}: ${typeOf(field.type)}`);
      return fields.length === 0 ? "Readonly<Record<string, never>>" : `{ ${fields.join("; ")} }`;
    }
    case "newtype":
      return typeOf(declaration.wraps);
    case "unit":
      return "Readonly<Record<string, never>>";
    case "sum":
      return alternatives(declaration.cases, declaration.form, names, declared, typeOf);
  }
}

/** A set of alternatives, as the form it travels in writes each of them. */
function alternatives(
  cases: readonly Shape[],
  form: Form,
  names: Map<string, string>,
  declared: Map<string, Declaration>,
  typeOf: (shape: Shape) => string,
): string {
  if (form.is === "enumeration") {
    return cases.map((each) => JSON.stringify(tagOf(each))).join(" | ");
  }
  return cases.map((each) => {
    const tag = `readonly ${property(form.tag)}: ${JSON.stringify(tagOf(each))}`;
    if (each.is === "declared") {
      const declaration = declared.get(key(each));
      if (declaration?.is === "unit") {
        return `{ ${tag} }`;
      }
      if (declaration?.is === "product") {
        return `({ ${tag} } & ${names.get(key(each))})`;
      }
    }
    // A newtype or a primitive keeps what it is written as, under a key of its own beside the tag.
    return `{ ${tag}; readonly ${property(form.contents)}: ${typeOf(each)} }`;
  }).join(" | ");
}

function tagOf(shape: Shape): string {
  switch (shape.is) {
    case "declared":
      return shape.name;
    case "scalar":
      return PRIMITIVE_TAGS[shape.scalar];
    default:
      throw new Error(`a case is a declaration or a primitive, and this is ${shape.is}`);
  }
}

function written(shape: Shape, names: Map<string, string>, declared: Map<string, Declaration>): string {
  const typeOf = (inner: Shape): string => written(inner, names, declared);
  switch (shape.is) {
    case "scalar":
      switch (shape.scalar) {
        case "int":
        case "decimal":
          return "Numeric";
        case "bool":
          return "boolean";
        default:
          return "string";
      }
    case "declared":
      return names.get(key(shape)) ?? "unknown";
    case "list":
    case "set":
      return `readonly (${typeOf(shape.of)})[]`;
    case "map":
      return `Readonly<Record<string, ${typeOf(shape.value)}>>`;
    case "option":
      return `${typeOf(shape.of)} | null`;
    case "union":
      return alternatives(shape.crossing.cases, shape.crossing.form, names, declared, typeOf);
  }
}
