// A TypeScript binding of a Souther program, written from what its module says it offers.
//
// Everything written here is read off the module's surface: the types its values cross as, the
// behaviors it offers, what it reaches out for, and the types a caller may read a value of on its
// own. Nothing about a model is decided here, so a case renamed in the model is a type renamed in
// the binding, and a page that still names the old one does not compile.

import { type Declaration, type Form, keyOf as key, type Shape, type Surface, tagOf } from "./surface.ts";

/**
 * What no name the binding declares at its top may be: what TypeScript reserves, what a type alias
 * cannot be called, and what the binding itself declares or reads there. A declaration a model
 * calls one of these is given another name, rather than the binding declaring two things under one
 * or a type of the model standing where the binding meant TypeScript's own.
 */
const RESERVED: ReadonlySet<string> = new Set([
  // What JavaScript reserves, in strict code and in a module.
  "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do",
  "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in",
  "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try",
  "typeof", "var", "void", "while", "with", "implements", "interface", "let", "package",
  "private", "protected", "public", "static", "yield", "await", "arguments", "eval",
  // What a type alias cannot be called.
  "any", "unknown", "never", "string", "number", "boolean", "symbol", "object", "bigint",
  "undefined", "type", "as", "satisfies",
]);

/**
 * What the binding itself declares at its top, which a model's declaration does not displace.
 *
 * Every one of these is written into the binding from here and only from here, and the binding names
 * nothing else at its top but the types `Names` hands out: none of TypeScript's own (`Record`,
 * `Promise`), which a model's type of the same name would stand in for. So a name the binding comes
 * to declare is reserved by being declared, and no list of reserved names can fall behind it.
 */
const OWN = {
  runtime: "souther",
  fingerprint: "FINGERPRINT",
  supplied: "Supplied",
  bound: "Bound",
  load: "load",
} as const;
const R = OWN.runtime;

/** A value with no field, written without naming TypeScript's `Readonly` or `Record`. */
const NOTHING = "{ readonly [key: string]: never }";

/** Hands out names no two of which are the same and none of which is reserved. */
class Names {
  readonly #taken: Set<string>;

  constructor(taken: Iterable<string>) {
    this.#taken = new Set(taken);
  }

  /** `wanted`, as an identifier, or the first of `wanted_2`, `wanted_3`… that nothing has. */
  claim(wanted: string): string {
    const base = identifier(wanted);
    let name = base;
    for (let n = 2; this.#taken.has(name); n++) {
      name = `${base}_${n}`;
    }
    this.#taken.add(name);
    return name;
  }
}

/** `name` as TypeScript can write an identifier: what it cannot hold becomes `_`. */
function identifier(name: string): string {
  const written = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(written) ? written : `_${written}`;
}

/**
 * The binding of a module whose surface is `surface`, as TypeScript source.
 *
 * What the model names is the binding's to call whatever it likes only where a property says it: a
 * module, a behavior and a type a value is read as are each a property, under the name the model
 * gives it, so `bound.modules.cart.price`, `bound.decode.cart.Sku` and `bound.form.cart.Cart`. What is declared at the top
 * — a type for each declaration — is named by `Names`, apart from what TypeScript reserves and what
 * the binding declares itself, and the runtime is read through one name, so no type of the model's
 * stands in for one of the runtime's.
 *
 * @param fingerprint what identifies the surface (`fingerprintOf`), which the binding refuses any
 *     other module than one carrying
 * @param runtime what the binding imports the runtime as
 */
export function bindingFor(surface: Surface, fingerprint: string, runtime = "@souther/wasm"): string {
  const names = namesOf(surface.declarations);
  const declared = new Map(surface.declarations.map((each) => [key(each), each]));
  const typeOf = (shape: Shape): string => written(shape, names, declared);
  const out: string[] = [
    "// Generated by @souther/wasm from a module's souther:surface. Do not edit: generate it again",
    "// from the module instead.",
    "",
    `import * as ${R} from ${JSON.stringify(runtime)};`,
    "",
    "/** What identifies the surface this binding was generated from; a module carrying another is refused. */",
    `export const ${OWN.fingerprint} = ${JSON.stringify(fingerprint)};`,
    "",
  ];

  for (const declaration of surface.declarations) {
    out.push(`/** \`${declaration.module}.${declaration.name}\`${declaration.published === false ? ", which its module keeps" : ""}. */`);
    out.push(`export type ${names.get(key(declaration))} = ${declarationType(declaration, typeOf, names, declared)};`);
    out.push("");
  }

  // What the host has to supply is every behavior the program reaches out for, whether its module
  // publishes it or keeps it: a kept one is reached for all the same.
  const reaching = surface.modules.flatMap((module) => module.behaviors
    .filter((behavior) => behavior.reachOut !== undefined)
    .map((behavior) => ({ behavior, named: `${module.name}.${behavior.name}` })));
  out.push("/** What answers each behavior the program reaches out for. */");
  out.push(`export interface ${OWN.supplied} {`);
  for (const { behavior, named } of reaching) {
    out.push(`  readonly ${JSON.stringify(named)}: (${parameters(behavior.parameters, typeOf)}) => ${typeOf(behavior.answers)};`);
  }
  out.push("}");
  out.push("");

  // What a caller may call is what a module publishes and nothing outside answers.
  const offered = surface.modules.map((module) => ({
    module,
    behaviors: module.behaviors.filter((behavior) => behavior.export !== undefined && behavior.reachOut === undefined),
  }));
  const decodable = new Map<string, Declaration[]>();
  for (const declaration of surface.declarations.filter((each) => each.decode !== undefined)) {
    decodable.set(declaration.module, [...decodable.get(declaration.module) ?? [], declaration]);
  }

  out.push("/** The program, loaded: each module's behaviors, and Raoh decoders of each type a value can be read as on its own, of a value and of what a form gives. */");
  out.push(`export interface ${OWN.bound} {`);
  out.push(`  readonly program: ${R}.Program;`);
  out.push("  readonly modules: {");
  for (const { module, behaviors } of offered) {
    out.push(`    readonly ${property(module.name)}: {`);
    for (const behavior of behaviors) {
      out.push(`      ${property(behavior.name)}(${parameters(behavior.parameters, typeOf)}): ${R}.Reading<${typeOf(behavior.answers)}>;`);
    }
    out.push("    };");
  }
  out.push("  };");
  for (const [reading, decoderType] of [["decode", "Decoder"], ["form", "FormDecoder"]]) {
    out.push(`  readonly ${reading}: {`);
    for (const [module, declarations] of decodable) {
      out.push(`    readonly ${property(module)}: {`);
      for (const declaration of declarations) {
        out.push(`      readonly ${property(declaration.name)}: ${R}.${decoderType}<${names.get(key(declaration))}>;`);
      }
      out.push("    };");
    }
    out.push("  };");
  }
  out.push("}");
  out.push("");

  const optional = reaching.length === 0 ? " = {}" : "";
  out.push("/** Loads the module this binding was generated from, and refuses any other. */");
  // What it answers is a promise of the binding, which TypeScript says without being told: the
  // binding names no global type, and a model's `Promise` cannot stand in for one it does not name.
  out.push(`export async function ${OWN.load}(source: ${R}.Source, supplied: ${OWN.supplied}${optional}) {`);
  out.push(`  const program = await ${R}.load(source, supplied as unknown as ${R}.Supplied, ${OWN.fingerprint});`);
  out.push(`  const bound: ${OWN.bound} = {`);
  out.push("    program,");
  out.push("    modules: {");
  for (const { module, behaviors } of offered) {
    out.push(`      ${property(module.name)}: {`);
    for (const behavior of behaviors) {
      // The arguments are named by place and nothing else, so no name the model gave a parameter
      // stands for `program` here.
      const names = behavior.parameters.map((_, at) => `argument${at}`).join(", ");
      out.push(`        ${property(behavior.name)}: (${names}) => program.call(${JSON.stringify(behavior.export as string)}, [${names}]),`);
    }
    out.push("      },");
  }
  out.push("    },");
  for (const [reading, made] of [["decode", "decoder"], ["form", "formDecoder"]]) {
    out.push(`    ${reading}: {`);
    for (const [module, declarations] of decodable) {
      out.push(`      ${property(module)}: {`);
      for (const declaration of declarations) {
        out.push(`        ${property(declaration.name)}: program.${made}(${JSON.stringify(key(declaration))}),`);
      }
      out.push("      },");
    }
    out.push("    },");
  }
  out.push("  };");
  out.push("  return bound;");
  out.push("}");
  return out.join("\n") + "\n";
}

/** A property's name as TypeScript writes it: bare where it can be, quoted where it cannot. */
function property(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/**
 * What each declaration is called in the binding: its own name where no other module declares one
 * by that name, and its module's before it where one does, since a type is its module and its name.
 * Those that need no module are named first, so one written as `AX` in module `c` keeps its name
 * where `a.X` would be written the same way; and whatever is still taken is told apart by a number.
 */
function namesOf(declarations: readonly Declaration[]): Map<string, string> {
  const count = new Map<string, number>();
  for (const each of declarations) {
    count.set(each.name, (count.get(each.name) ?? 0) + 1);
  }
  const shared = (each: Declaration): boolean => (count.get(each.name) ?? 0) > 1;
  const names = new Names([...RESERVED, ...Object.values(OWN)]);
  const named = new Map<string, string>();
  for (const each of declarations.filter((it) => !shared(it))) {
    named.set(key(each), names.claim(each.name));
  }
  for (const each of declarations.filter(shared)) {
    named.set(key(each), names.claim(each.module.split(".").map(capitalised).join("") + each.name));
  }
  return named;
}

function capitalised(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/**
 * A signature's parameters, under the names the model gave them where TypeScript can write those,
 * which is what a caller reads off the signature; under another where it cannot.
 */
function parameters(
  declared: readonly { readonly name: string | null; readonly type: Shape }[],
  typeOf: (shape: Shape) => string,
): string {
  const names = new Names(RESERVED);
  return declared.map((each, at) => `${names.claim(each.name ?? `argument${at}`)}: ${typeOf(each.type)}`)
    .join(", ");
}

function declarationType(
  declaration: Declaration,
  typeOf: (shape: Shape) => string,
  names: Map<string, string>,
  declared: Map<string, Declaration>,
): string {
  switch (declaration.is) {
    case "product": {
      // An optional field is the boundary's to read as nothing where it is left out and where it
      // is written as null, so its type says both: what a type says is what the boundary takes, and
      // a field typed narrower would refuse a value every backend reads. That a module leaves it out
      // when it writes one is how it writes, and a reader handling both loses nothing.
      const fields = declaration.fields.map((field) => field.type.is === "option"
        ? `readonly ${property(field.name)}?: ${typeOf(field.type)}`
        : `readonly ${property(field.name)}: ${typeOf(field.type)}`);
      return fields.length === 0 ? NOTHING : `{ ${fields.join("; ")} }`;
    }
    case "newtype":
      return typeOf(declaration.wraps);
    case "unit":
      return NOTHING;
    case "sum":
      return alternatives(declaration.cases, declaration.form, names, declared, typeOf);
  }
}

/** A set of alternatives, as the form it travels in writes each of them. */
function alternatives(
  cases: readonly Shape[],
  form: Form,
  names: Map<string, string>,
  declared: Map<string, Declaration>,
  typeOf: (shape: Shape) => string,
): string {
  if (form.is === "enumeration") {
    return cases.map((each) => JSON.stringify(tagOf(each))).join(" | ");
  }
  return cases.map((each) => {
    const tag = `readonly ${property(form.tag)}: ${JSON.stringify(tagOf(each))}`;
    if (each.is === "declared") {
      const declaration = declared.get(key(each));
      if (declaration?.is === "unit") {
        return `{ ${tag} }`;
      }
      if (declaration?.is === "product") {
        return `({ ${tag} } & ${names.get(key(each))})`;
      }
    }
    // A newtype or a primitive keeps what it is written as, under a key of its own beside the tag.
    return `{ ${tag}; readonly ${property(form.contents)}: ${typeOf(each)} }`;
  }).join(" | ");
}

function written(shape: Shape, names: Map<string, string>, declared: Map<string, Declaration>): string {
  const typeOf = (inner: Shape): string => written(inner, names, declared);
  switch (shape.is) {
    case "scalar":
      switch (shape.scalar) {
        // As Raoh's long() and decimal() give them, so nothing counted or priced is rounded.
        case "int":
          return "bigint";
        case "decimal":
          return `${R}.Decimal`;
        case "bool":
          return "boolean";
        default:
          return "string";
      }
    case "declared":
      return names.get(key(shape)) ?? "unknown";
    case "list":
    case "set":
      return `readonly (${typeOf(shape.of)})[]`;
    case "map":
      return `{ readonly [key: string]: ${typeOf(shape.value)} }`;
    case "option":
      return `${typeOf(shape.of)} | null`;
    case "union":
      return alternatives(shape.crossing.cases, shape.crossing.form, names, declared, typeOf);
  }
}
